name: Merge-Checks
on:
  push:
    branches:
      - main

jobs:
  check_1:
    name: "Check 1"
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo Hello World!
      - name: Force fail
        run: exit 1
